<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Bai2.css" />
    <Content Remove="wwwroot\Bai2.html" />
    <Content Remove="wwwroot\Bai3.css" />
    <Content Remove="wwwroot\Bai3.html" />
    <Content Remove="wwwroot\Bai4.css" />
    <Content Remove="wwwroot\Bai4.html" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Bai4.css" />
    <None Include="wwwroot\Bai4.html" />
    <None Include="wwwroot\Bai3.css" />
    <None Include="wwwroot\Bai3.html" />
    <None Include="wwwroot\Bai2.css" />
    <None Include="wwwroot\Bai2.html" />
    <None Include="wwwroot\Bai1.css" />
    <None Include="wwwroot\Bai1.html" />
  </ItemGroup>

</Project>
